name: Build & Deploy to TestFlight

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
      - run: flutter pub get
      - run: flutter build ios --release --no-codesign
      - name: Install pods & archive
        run: |
          cd ios
          pod install
          xcodebuild -workspace Runner.xcworkspace \
            -scheme Runner \
            -configuration Release \
            -destination 'generic/platform=iOS' \
            -archivePath ../build/ios/Runner.xcarchive \
            archive
          xcodebuild -exportArchive \
            -archivePath ../build/ios/Runner.xcarchive \
            -exportOptionsPlist ../ExportOptions.plist \
            -exportPath ../build/ios/ipa
      - name: Upload to TestFlight
        uses: apple-actions/upload-testflight-build@v1
        with:
          app-path: build/ios/ipa/Runner.ipa
          issuer-id: ${{ secrets.APPSTORE_ISSUER_ID }}
          key-id: ${{ secrets.APPSTORE_KEY_ID }}
          private-key: ${{ secrets.APPSTORE_PRIVATE_KEY }}
